### ISSUE TITLE
Add option to add Brand on back end

### ISSUE THREAD

**Issue by akaExposed** [buildsgg/buildsgg#24]
**Is your feature request related to a problem? Please describe.**

Can't add items to database because brand isn't available

People are requesting brands that aren't currently listed on the back end, would like to be able to add them as needed.

**Describe the solution you'd like**

Allow add new brand when someone submits a request, let whoever is submitting request to type brand in and allow us to approve it if brand is legit.

**Comment by bashgeek** [comment]
Thanks for the report.

We already discussed this internally a couple of days ago and this is already implemented. However, this does not show up in the part requests and is handled separately for various reasons. It already is available for users by clicking "Can't find the brand you used? Let us know about it!" during the request process. Since brands and our brand-pages will be heavily customisable for the brand owner in the future we do want to keep a close eye on every brand we add and decide on a case-by-case basis if we really want to add a brand or not.

Anyway, this should only be a real issue in the first few weeks, after that all important brands should be available - if not already.
